[package]
name = "stabled"
author = "Stabled Labs"
about = "ggwp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
cli-table = "0.4.7"
indoc = "2.0.3"
which = "4.4.0"
zbus = "3.14.1"
psutil = { git = "https://github.com/servicer-labs/rust-psutil", default-features = false, features = ["process"] }
bytesize = "1.2.0"

