name: servicer # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Simplify Service Management on systemd # 79 char long summary
description:  A CLI tool for service management on systemd.

apps:
  servicer:
    command: bin/servicer
    plugs: [home]

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  servicer:
    # See 'snapcraft plugins'
    plugin: rust
    source: .
    build-packages: [cargo, rustc]
